#!/bin/bash

ROOT="$1"
FILE="$2"
TASK="$3"

DIR="$FILE"
while true; do
    DIR=`dirname "$DIR"`

    ls "$DIR/Makefile" 1>/dev/null 2>/dev/null
    if [ "$?" -eq 0 ]; then
        echo "Project: `basename $DIR`"
        make auto --no-print-directory -C "$DIR" "$TASK"
        exit
    fi

    if [ "$ROOT" == "$DIR" ]; then
        exit
    fi
done
