ADD_TRACKER(HEAP_TRACKER_ID, HEAP_TRACKER_NAME, HEAP_TRACKER_SIZE)
ADD_TRACKER(CMD_TRACKER_ID, CMD_TRACKER_NAME, CMD_TRACKER_SIZE)
ADD_TRACKER(STREAM_TRACKER_ID, STREAM_TRACKER_NAME, STREAM_TRACKER_SIZE)
